directories:
  output: release
  buildResources: build
appId: com.smartsender.app
productName: Smart Sender
win:
  target:
    - target: nsis
      arch:
        - x64
nsis:
  oneClick: false
  perMachine: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
files: []
electronVersion: 41.2.1
